import React from "react";

const TermsOfUse = () => {

    return (
        <div className="container">
            <h3>AudioCloud Terms of Use</h3>
            <p>Welcome to AudioCloud®, a service provided by AudioCloud Global Limited &amp; Co. KG (<strong>"AudioCloud"</strong>, <strong>"we"</strong> <strong>"our"</strong>, or <strong>"us"</strong>).</p>
            <p>These Terms of Use govern your use of soundcloud.com and m.soundcloud.com (together, the <strong>"Website"</strong>), our mobile and desktop apps (our <strong>"Apps"</strong>) and all related players, widgets, tools, features, applications, data, software, APIs (which may also be subject to separate API Terms of Use) and other services provided by AudioCloud (the <strong>"Services"</strong>).</p>
            <p>These Terms of Use, together with our Community Guidelines and any other terms specifically referred to in any of those documents, all of which are incorporated by reference into these Terms of Use, constitute a legally binding contract (the <strong>"Agreement"</strong>), between you and AudioCloud in relation to your use of the Website, Apps and Services (together, the <strong>"Platform"</strong>).</p>
            <p>Please also be sure to review our <a href="/pages/privacy">Privacy Policy</a> and <a href="/pages/cookies">Cookies Policy</a> for more information on how we collect and use data relating to the use and performance of the Platform, as well as our responsibilities and your rights in relation to any processing of your personal data.</p>
            <p>These Terms of Use consist of the following sections:</p>
            <ul>
                <li><p><a href="#acceptance-of-terms-of-use">Acceptance of Terms of Use</a>
                    Basically, by using AudioCloud® you accept our Terms of Use and <a href="/community-guidelines">Community Guidelines</a> and agree to abide by them.</p></li>
                <li><p><a href="#changes-to-terms-of-use">Changes to Terms of Use</a>
                    This section explains that our terms of Use may change from time to time.</p></li>
                <li><p><a href="#description-of-the-platform">Description of the Platform</a>
                    This provides a general description of the Platform, its features and functionality.</p></li>
                <li><p><a href="#your-soundcloud-account">Your AudioCloud account</a>
                    This section explains your responsibilities should you choose to register for a AudioCloud® account.</p></li>
                <li><p><a href="#your-use-of-the-platform">Your Use of the platform</a>
                    This section sets out your right to use the Platform, and the conditions that apply to your use of the Platform.</p></li>
                <li><p><a href="#your-content">Your content</a>
                    This section deals with ownership of your content, and includes your agreement not to upload anything that infringes on anyone else’s rights.</p></li>
                <li><p><a href="#grant-of-license">Grant of license</a>
                    This section explains how your content will be used on AudioCloud® and the permissions that you grant by uploading your content - for example, the right for other users to listen to your sounds.</p></li>
                <li><p><a href="#representations-and-warranties">Representations and warranties</a>
                    This section includes important promises and guarantees that you give when uploading content to AudioCloud® - in particular, your promise that everything you upload and share is owned by you and won’t infringe anyone else’s rights.</p></li>
                <li><p><a href="#liability-for-content">Liability for content</a>
                    This section explains that AudioCloud is a hosting service and that its users are solely liable for material that they upload to AudioCloud®.</p></li>
                <li><p><a href="#reporting-infringements">Reporting infringements</a>
                    This section explains how to notify us of any content on AudioCloud® that you believe infringes your copyright or any other intellectual property right, or that is unlawful, abusive, defamatory or otherwise contrary to our Terms of Use or <a href="/community-guidelines">Community Guidelines</a>. You can find further information on reporting copyright infringement on our <a href="/pages/copyright">Copyright Information</a> pages.</p></li>
                <li><p><a href="#third-party-websites-and-services">Third party websites and services</a> Through AudioCloud® you may have access to other websites and services. This section explains
                    that these are separate third party services that are not under the control of AudioCloud.</p></li>
                <li><p><a href="#blocking-and-removal-of-content">Blocking and removal of content</a>
                    This section makes it clear that AudioCloud may block or remove content from the Platform.</p></li>
                <li><p><a href="#repeat-infringers">Repeat infringers</a>
                    Users who repeatedly infringe third party rights or breach our Terms of Use or <a href="/community-guidelines">Community Guidelines</a> risk having their AudioCloud® accounts suspended or terminated, as explained in this section.</p></li>
                <li><p><a href="#disclaimer">Disclaimer</a>
                    This section explains that AudioCloud® cannot give any guarantees that the Platform will always be available – sometimes even a platform as awesome as ours will have a few problems.</p></li>
                <li><p><a href="#limitation-of-liability">Limitation of liability</a>
                    This section explains some of those things that AudioCloud will not be liable for. Please make sure you read and understand this section.</p></li>
                <li><p><a href="#indemnification">Indemnification</a>
                    If you use the Platform in a way that results in damage to us, you will need to take responsibility for that.</p></li>
                <li><p><a href="#data-protection-privacy-and-cookies">Data protection, privacy and cookies</a>
                    It is really important to us that you understand how we use your personal information. All information is collected, stored and used in accordance with our <a href="/pages/privacy">Privacy Policy</a>, so please make sure that you read and understand that policy. Like most other websites, we also use cookies to help us analyze how people use AudioCloud, so that we can keep improving our service. Our use of cookies is explained in our <a href="/pages/cookies">Cookies Policy</a>.</p></li>
                <li><p><a href="#meetups">Meetups</a>
                    This section deals with AudioCloud® meetups and explains that these are not "official" AudioCloud events, so we cannot be responsible for anything that happens at meetups.</p></li>
                <li><p><a href="#competitions-and-other-promotions">Competitions and other promotions</a>
                    This section deals with competitions, contests and sweepstakes on AudioCloud®. These are not run by AudioCloud, and therefore we cannot be responsible for them. If you want to run your own competition on AudioCloud, make sure you read and understand our Competition Terms.</p></li>
                <li><p><a href="#use-of-soundcloud-players-and-widget">Use of AudioCloud players and widget</a>
                    This section includes a few restrictions on how you can use our players and widgets – basically, don’t try to use our players to create a new music or audio streaming service.</p></li>
                <li><p><a href="#subscriptions-and-gift-codes">Subscriptions and gift codes</a>
                    This section links you to information explaining how to purchase "Pro" and "Next Pro" plans and "AudioCloud Go" subscriptions as well as gift codes and how you can cancel your purchases in certain circumstances.</p></li>
                <li><p><a href="#changes-to-the-platform-accounts-and-pricing">Changes to the Platform, accounts and pricing</a>
                    From time to time, we may need to make some changes to AudioCloud®. This section explains your rights in this situation.</p></li>
                <li><p><a href="#termination">Termination</a>
                    This section explains how you can terminate your AudioCloud® account, and the grounds on which we can terminate your use of AudioCloud®.</p></li>
                <li><p><a href="#assignment-to-third-parties">Assignment to third parties</a>
                    This section deals with AudioCloud’s right to transfer this agreement to someone else.</p></li>
                <li><p><a href="#severability">Severability</a>
                    This is a standard legal provision, which says that any term that is not valid will be removed from the agreement without affecting the validity of the rest of the agreement.</p></li>
                <li><p><a href="#entire-agreement">Entire agreement</a>
                    Your use of AudioCloud® is governed by these Terms of Use, our <a href="/pages/privacy">Privacy Policy</a>, <a href="/pages/cookies">Cookies Policy</a> and <a href="/legal/community-guidelines">Community Guidelines</a>. Any changes need to be made in writing.</p></li>
                <li><p><a href="#third-party-rights">Third party rights</a>
                    These Terms of Use apply to the relationship between you and AudioCloud only.</p></li>
                <li><p><a href="#applicable-law-and-jurisdiction">Applicable law and jurisdiction</a>
                    All of our documents are generally governed by German law.</p></li>
                <li><p><a href="#disclosures">Disclosures</a>
                    This section provides information about AudioCloud, including how to contact us.</p></li>
            </ul>
            <h2 id="acceptance-of-terms-of-use">Acceptance of Terms of Use</h2>
            <p>Please read these Terms of Use, <a href="/pages/privacy">Privacy Policy</a>, <a href="/pages/cookies">Cookies Policy</a> and <a href="/community-guidelines">Community Guidelines</a>, very carefully. <strong>If you do not agree to any of the provisions set out in those documents, you should not use the Website, Apps or any of the Services.</strong> By accessing or using the Platform, registering an account, or by viewing, accessing, streaming, uploading or downloading any information or content from or to the Platform, you represent and warrant that you have read and understood the Terms of Use and <a href="/community-guidelines">Community Guidelines</a>, will abide by them, and that you are either 18 years of age or more, or the applicable age of majority in your jurisdiction, or if you are under 18 years of age or the age of majority in your jurisdiction, you are 16 years of age or more if you reside in the European Union and UK or 13 years of age or more if you reside in the United States or anywhere else.</p>
            <h2 id="changes-to-terms-of-use">Changes to Terms of Use</h2>
            <p>We reserve the right to change, alter, replace or otherwise modify these Terms of Use at any time, for example to address legal or regulatory changes or changes to features or functionality made available through the Platform, at our discretion. The date of last modification is stated at the end of these Terms of Use. It is your responsibility to check this page from time to time for updates.</p>
            <p>When we make any material changes to these Terms of Use, we will provide you with prominent notice under the circumstances, including for example displaying a notice within the Platform and/or by sending you an email to the email address that you have provided us or a message to your AudioCloud account, and the revised Terms of Use will become effective two (2) weeks after such notification.</p>
            <p>You will have no obligation to continue using the Platform following any such notification, but if you do not terminate your account as described in the <a href="#termination">Termination</a> section below during such two (2) week period, your continued use of the Platform after the end of that two (2) week period will constitute your acceptance of the revised Terms of Use.</p>
            <h2 id="description-of-the-platform">Description of the Platform</h2>
            <p>The Platform is a hosting service. Registered users of the Platform may submit, upload and post audio, text, photos, pictures, graphics, comments, and other content, data or information (<strong>"Content"</strong>), which will be stored by AudioCloud at the direction of such registered users, and may be shared and distributed by such registered users, and other users of the Platform, using the tools and features provided as part of the Platform and accessible via the Website, Apps and elsewhere. The Platform also enables registered users to interact with one another and to contribute to discussions, and enables any user of the Website, Apps or certain Services (who may or may not be registered users of the Platform) to view, listen to and share Content uploaded and made available by registered users.</p>
            <p>The Platform also includes social and interactive features that enable users to engage with and learn from the AudioCloud community in order to build a following and ensure you get the content that interests you most. For example, users who upload content to AudioCloud will gain access to our creator stats feature, which provides creators with insights into how the content they upload fares among users, including which users are top listeners and downloaders of such content.</p>
            <p>Some features of our Platform are only available to registered users who subscribe to a certain Service (see <a href="#subscriptions-and-gift-codes">Subscriptions and Gift Codes</a> below). AudioCloud however remains free for users that choose not to subscribe to such Services. In order to make the Platform available for free and provide you with personally relevant features, we serve tailored ads on the Platform on behalf of third party advertisers. To that end, we use information that you make available to us when you interact with the Platform to inform the nature of the ads we show you and provide you with a customized experience. More information on how we use data to show you personalized ads is described in our <a href="/pages/privacy">Privacy Policy</a>.</p>
            <p>We may, from time to time, release new tools and resources on the Website, release new versions of our Apps, or introduce other services and/or features for the Platform. Any new services and features will be subject to these Terms of Use as well as any additional terms and conditions that we may release for those specific services or features.</p>
            <h2 id="your-soundcloud-account">Your AudioCloud account</h2>
            <p>You are not obliged to register to use the Platform. However, access to the Apps and certain Services is only available to registered users. As an example, our App, AudioCloud Pulse, enables registered users, who upload and make available their Content to other users, to receive instant feedback on the performance of their tracks, communicate with their listeners, and manage their Content anytime.</p>
            <p>In order for you to engage with other AudioCloud listeners and creators, we enable you to create and personalize a public profile on AudioCloud. To enable you to do that, you must provide us with the information you want to display on such profile.</p>
            <p>In order to help you to navigate and discover content on the Platform that interests you, as a registered user you will also receive auto-generated personalized recommendations of other content that might appeal to you, based on your listening habits.</p>
            <p>When you register to use the Platform, you will provide us with your email address, and will choose a username and password for your account. You must ensure that the email address that you provide is, and remains, valid. Your email address and any other information you chose to provide about yourself will be treated in accordance with our <a href="/pages/privacy">Privacy Policy</a>.</p>
            <p>You are solely responsible for maintaining the confidentiality and security of your username and password, and you will remain responsible for all use of your username and password, and all activity emanating from your account, whether or not such activity was authorized by you.</p>
            <p>If your username or password is lost or stolen, or if you believe that your account has been accessed by unauthorized third parties, you are advised to notify AudioCloud in writing, and should change your password at the earliest possible opportunity.</p>
            <p>We reserve the right to disallow, cancel, remove or reassign certain usernames and permalinks in appropriate circumstances, as determined by us in our sole discretion, and may, with or without prior notice, suspend or terminate your account if activities occur on that account which, in our sole discretion, would or might constitute a violation of these Terms of Use or our <a href="/community-guidelines">Community Guidelines</a>, or an infringement or violation of the rights of any third party, or of any applicable laws or regulations.</p>
            <p>You may terminate your account at any time as described in the <a href="#termination">Termination</a> section below.</p>
            <h2 id="your-use-of-the-platform">Your use of the Platform</h2>
            <p>Subject to your strict compliance with these Terms of Use and our <a href="/community-guidelines">Community Guidelines</a> at any and all times during your use of the Platform, AudioCloud grants you a limited, personal, non-exclusive, revocable, non-assignable and non-transferable right and license to use the Platform in order to view Content uploaded and posted to the Website, to listen to audio Content streamed from the Platform or offline and to share and download audio Content using the features of the Platform where the appropriate functionality has been enabled by the user who uploaded the relevant Content (the <strong>"Uploader"</strong>), and subject to the territorial availability of that feature and audio Content.</p>
            <p>In addition, if you register to use the Platform, and subject to your strict compliance with these Terms of Use and our <a href="/community-guidelines">Community Guidelines</a> at any and all times during your use of the Platform, AudioCloud grants you a limited, personal, non-exclusive, revocable, non-assignable and non-transferable right and license to:</p>
            <p>(i) submit, upload or post Content to and keep such Content available on the Platform strictly as permitted in accordance with these Terms of Use and any other applicable terms posted on the Website from time to time;</p>
            <p>(ii) participate in the community areas and communicate with other members of the AudioCloud® community strictly in accordance with these Terms of Use and our <a href="/community-guidelines">Community Guidelines</a>; and</p>
            <p>(iii) use Apps and other Services provided as part of the Platform strictly as permitted in accordance with these Terms of Use and any other terms applicable to those Apps or Services from time to time.</p>
            <p>The above licenses are conditional upon your strict compliance with these Terms of Use and our <a href="/community-guidelines">Community Guidelines</a> at any and all times during your use of the Platform, including, without limitation, the following:</p>
            <p>(i) You must not copy, rip or capture, or attempt to copy, rip or capture, any audio Content from the Platform or any part of the Platform, other than by means of download or store for offline listening in circumstances where the relevant Uploader has elected to permit downloads or offline listening of the relevant item of Content.</p>
            <p>(ii) You must not adapt, copy, republish, make available or otherwise communicate to the public, display, perform, transfer, share, distribute or otherwise use or exploit any Content on or from the Platform at any and all times, except (i) where such Content is Your Content at any and all times during your use of the applicable Content, or (ii) as permitted under these Terms of Use, and within the parameters set by the Uploader (for example, under the terms of Creative Commons licenses selected by the Uploader).</p>
            <p>(iii) You must not use any Content (other than Your Content) in any way that is designed to create a separate content service or that replicates any part of the Platform offering.</p>
            <p>(iv) You must not employ scraping or similar techniques to aggregate, repurpose, republish or otherwise make use of any Content.</p>
            <p>(v) You must not employ any techniques or make use of any services, automated or otherwise, designed to misrepresent the popularity of Your Content on the Platform, or to misrepresent your activity on the Platform, including without limitation by the use of bots, botnets, scripts, apps, plugins, extensions or other automated means to register accounts, log in, add followers to your account, play Content, follow or unfollow other users, send messages, post comments, or otherwise to act on your behalf, particularly where such activity occurs in a multiple or repetitive fashion. You must not offer or promote the availability of any such techniques or services to any other users of the Platform.</p>
            <p>(vi) You must not alter or remove, or attempt to alter or remove, any trademark, copyright or other proprietary or legal notices contained in, or appearing on, the Platform or any Content appearing on the Platform (other than Your Content).</p>
            <p>(vii) You must not, and must not permit any third party to, copy or adapt the object code of the Website or any of the Apps or Services, or reverse engineer, reverse assemble, decompile, modify or attempt to discover any source or object code of any part of the Platform, or circumvent or attempt to circumvent or copy any copy protection mechanism or territorial restrictions or access any rights management information pertaining to Content other than Your Content.</p>
            <p>(viii) You must not use the Platform to upload, post, store, transmit, display, copy, distribute, promote, make available, continue to make available or otherwise communicate to the public:</p>
            <ul>
                <li>any Content that is abusive, libellous, defamatory, pornographic or obscene, that promotes or incites violence, terrorism, illegal acts, or hatred on the grounds of race, ethnicity, cultural identity, religious belief, disability, gender, identity or sexual orientation, or is otherwise objectionable in AudioCloud’s reasonable discretion;</li>
                <li>any information, Content or other material that violates, plagiarizes, misappropriates or infringes the rights of third parties including, without limitation, copyright, trademark rights, rights of privacy or publicity, confidential information or any other right; or</li>
                <li>any Content that violates, breaches or is contrary to any law, rule, regulation, court order or is otherwise is illegal or unlawful in AudioCloud’s reasonable opinion;</li>
                <li>any material of any kind that contains any virus, Trojan horse, spyware, adware, malware, bot, time bomb, worm, or other harmful or malicious component, which or might overburden, impair or disrupt the Platform or servers or networks forming part of, or connected to, the Platform, or which does or might restrict or inhibit any other user's use and enjoyment of the Platform; or</li>
                <li>any unsolicited or unauthorized advertising, promotional messages, spam or any other form of solicitation.</li>
            </ul>
            <p>(ix) You must not commit or engage in, or encourage, induce, solicit or promote, any conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate any law or regulation.</p>
            <p>(x) You must not rent, sell or lease access to the Platform, or any Content on the Platform, although this shall not prevent you from including links from Your Content to any legitimate online download store from where any item of Your Content may be purchased.</p>
            <p>(xi) You must not deliberately impersonate any person or entity or otherwise misrepresent your affiliation with a person or entity, for example, by registering an account in the name of another person or company, or sending messages or making comments using the name of another person.</p>
            <p>(xii) You must not stalk, exploit, threaten, abuse or otherwise harass another user, or any AudioCloud employee.</p>
            <p>(xiii) You must not use or attempt to use another person's account, password, or other information, unless you have express permission from that other person.</p>
            <p>(xiv) You must not sell or transfer, or offer to sell or transfer, any AudioCloud account to any third party without the prior written approval of AudioCloud.</p>
            <p>(xv) You must not collect or attempt to collect personal data, or any other kind of information about other users, including without limitation, through spidering or any form of scraping.</p>
            <p>(xvi) You must not violate, circumvent or attempt to violate or circumvent any data security measures employed by AudioCloud or any Uploader; access or attempt to access data or materials which are not intended for your use; log into, or attempt to log into, a server or account which you are not authorized to access; attempt to scan or test the vulnerability of AudioCloud’s servers, system or network or attempt to breach AudioCloud’s data security or authentication procedures; attempt to interfere with the Website or the Services by any means including, without limitation, hacking AudioCloud’s servers or systems, submitting a virus, overloading, mail-bombing or crashing. Without limitation to any other rights or remedies of AudioCloud under these Terms of Use, AudioCloud reserves the right to investigate any situation that appears to involve any of the above, and may report such matters to, and co-operate with, appropriate law enforcement authorities in prosecuting any users who have participated in any such violations.</p>
            <p>You agree to comply with the above conditions at any and all times during your use of the Platform, and acknowledge and agree that AudioCloud has the right, in its sole discretion, to terminate your account or take such other action as we see fit if you breach any of the above conditions or any of the other terms of these Terms of Use. This may include taking court action and/or reporting offending users to the relevant authorities.</p>
            <h2 id="your-content">Your content</h2>
            <p>Any and all audio, text, photos, pictures, graphics, comments, and other content, data or information that you upload, store, transmit, submit, exchange or make available to or via the Platform (hereinafter <strong>"Your Content"</strong>) is generated, owned and controlled solely by you, and not by AudioCloud.</p>
            <p>AudioCloud does not claim any ownership rights in Your Content, and you hereby expressly acknowledge and agree that Your Content remains your sole responsibility.</p>
            <p>Without prejudice to the conditions set forth in <a href="#your-use-of-the-platform">Your Use of the Platform</a> you must not upload, store, distribute, send, transmit, display, perform, make available, continue to make available or otherwise communicate to the public any Content to which you do not hold the necessary rights. In particular, <strong>any unauthorized use of copyright protected works within Your Content (including by way of reproduction, distribution, modification, adaptation, public display, public performance, preparation of derivative works, making available or otherwise communicating to the public via the Platform), independent of whether it is or becomes unauthorized at a later point, may constitute an infringement of third party rights and is <em>strictly prohibited</em></strong>. Any such infringements may result in termination of your access to the Platform as described in the <a href="#repeat-infringers">Repeat Infringers</a> section below, and may also result in civil litigation or criminal prosecution by or on behalf of the relevant rightsholder.</p>
            <p>Not all unauthorized uses of copyright protected works constitute an infringement. Users in the European Union can use copyright protected works under certain exceptions or limitations to copyright, namely quotation, criticism, review, use for the purpose of caricature, parody or pastiche.</p>
            <p>We may, from time to time, invite or provide you with means to provide feedback regarding the Platform, and in such circumstances, any feedback you provide will be deemed non-confidential and AudioCloud shall have the right, but not the obligation, to use such feedback on an unrestricted basis.</p>
            <h2 id="grant-of-license">Grant of license</h2>
            <p>By uploading or posting Your Content to the Platform, you initiate an automated process to transcode any audio Content and direct AudioCloud to store Your Content on our servers, from where you may control and authorize the use, ways of reproduction, transmission, distribution, public display, public performance, making available (including whether users will be permitted to listen to your Content offline) and other communication to the public of Your Content on the Platform and elsewhere using the Services. To the extent it is necessary in order for AudioCloud to provide you with any of the aforementioned hosting services, to undertake any of the tasks set forth in these Terms of Use, including the distribution of advertising or other promotional material on our Platform and/or to enable your use of the Platform, you hereby grant such licenses to AudioCloud on a limited, worldwide, non-exclusive, royalty-free and fully paid basis.</p>
            <p>By uploading Your Content to the Platform, you also grant a limited, worldwide, non-exclusive, royalty-free, fully paid up, license to other users of the Platform, and to operators and users of any other websites, apps and/or platforms to which Your Content has been shared or embedded using the Services (<strong>"Linked Services"</strong>), to use, copy, listen to offline, repost, transmit or otherwise distribute, publicly display, publicly perform, adapt, prepare derivative works of, compile, make available and otherwise communicate to the public, Your Content utilizing the features of the Platform from time to time, and within the parameters set by you using the Services. You can limit and restrict the availability of certain of Your Content to other users of the Platform, and to users of Linked Services, at any time using the permissions tab in the track edit section for each sound you upload, subject to the provisions of the <a href="#disclaimer">Disclaimer</a> section below. Notwithstanding the foregoing, nothing in these Terms of Use grants any rights to any other user of the Platform with respect to any proprietary name, logo, trademark or service mark uploaded by you as part of Your Content (for example, your profile picture) (<strong>"Marks"</strong>), other than the right to reproduce, publicly display, make available and otherwise communicate to the public those Marks, automatically and without alteration, as part of the act of reposting sounds with which you have associated those Marks.</p>
            <p>The licenses granted in this section are granted separately with respect to each item of Your Content that you upload to the Platform. Licenses with respect to audio Content, and any images or text within your account, will (subject to the following paragraph of these Terms of Use) terminate automatically when you remove such Content from your account. Licenses with respect to comments or other contributions that you make on the Platform will be perpetual and irrevocable, and will continue notwithstanding any termination of your account.</p>
            <p>Removal of audio Content from your account will automatically result in the deletion of the relevant files from AudioCloud’s systems and servers. However, notwithstanding the foregoing, you hereby acknowledge and agree that once Your Content is distributed to a Linked Service, AudioCloud is not obligated to ensure the deletion of Your Content from any servers or systems operated by the operators of any Linked Service, or to require that any user of the Platform or any Linked Service deletes any item of Your Content. Furthermore, if you authorize any of Your Content to be available for offline listening, after deletion of an item of Your Content or removal from the ability for other users to listen to the applicable Content offline, the applicable Content may still be temporarily available to other users of the Platform who saved the applicable Content for offline listening on their devices, but no longer than 30 days from the time of deletion.</p>
            <p>Any Content other than Your Content is the property of the relevant Uploader, and is or may be subject to copyright, trademark rights or other intellectual property or proprietary rights. Such Content may not be downloaded, reproduced, distributed, transmitted, re-uploaded, republished, displayed, sold, licensed, made available or otherwise communicated to the public or exploited for any purposes except via the features of the Platform from time to time and within the parameters set by the Uploader on the Platform or with the express written consent of the Uploader. Where you repost another user’s Content, or include another user’s Content in a playlist or station or where you listen to another user’s Content offline, you acquire no ownership rights whatsoever in that Content. Subject to the rights expressly granted in this section, all rights in Content are reserved to the relevant Uploader.</p>
            <h2 id="representations-and-warranties">Representations and warranties</h2>
            <p>You hereby represent and warrant to AudioCloud as follows:
                (i) Your Content, and each and every part thereof, is an original work by you, or you have obtained all rights, licenses, consents and permissions necessary in order to use at any and all times during any applicable use, and (if and where relevant) to authorize AudioCloud to use, Your Content pursuant to these Terms of Use, including, without limitation, the right to upload, reproduce, store, transmit, distribute, share, publicly display, publicly perform, make available (including for listening offline) and otherwise communicate to the public Your Content, and each and every part thereof, on, through or via the Platform, any and all Services and any Linked Services.</p>
            <p>(ii) Your Content and the availability thereof on the Platform does not and will not infringe or violate the rights of any third party, including, without limitation, any intellectual property rights, performers’ rights, rights of privacy or publicity, or rights in confidential information.</p>
            <p>(iii) You have obtained any and all necessary consents, permissions and/or releases from any and all persons appearing in Your Content in order to include their name, voice, performance or likeness in Your Content and to publish the same on the Platform and via any Linked Services.</p>
            <p>(iv) Your Content, including any comments that you may post on the Website, is not and will not be unlawful, abusive, libellous, defamatory, pornographic or obscene, and will not promote or incite violence, terrorism, illegal acts, or hatred on the grounds of race, ethnicity, cultural identity, religious belief, disability, gender, identity or sexual orientation.</p>
            <p>(v) Your Content does not and will not create any liability on the part of AudioCloud, its subsidiaries, affiliates, successors, and assigns, and their respective employees, agents, directors, officers and/or shareholders.
                AudioCloud reserves the right to remove Your Content, suspend or terminate your access to the Platform and/or pursue all legal remedies if we believe that any of Your Content breaches any of the foregoing representations or warranties, or otherwise infringes another person's rights or violates any law, rule or regulation.</p>
            <h2 id="liability-for-content">Liability for content</h2>
            <p>You hereby acknowledge and agree that AudioCloud (i) stores content and other information at the direction, request and with the authorization of its users, (ii) acts merely as a passive conduit and/or host for the uploading, storage and distribution of such content, and (iii) plays no active role and gives no assistance in the presentation or use of the content. You are solely responsible for all of Your Content that you upload, post or distribute to, on or through the Platform, and to the extent permissible by law, AudioCloud excludes all liability with respect to all content (including Your Content) and the activities of its users with respect thereto.</p>
            <p>You hereby acknowledge and agree that AudioCloud cannot and does not review the content created or uploaded by its users, and neither AudioCloud nor its subsidiaries, affiliates, successors, assigns, employees, agents, directors, officers and shareholders has any obligation, and may, but does not undertake or assume any duty to, monitor the Platform for content that is inappropriate, that does or might infringe any third party rights, or has otherwise been uploaded in breach of these Terms of Use or applicable law.</p>
            <p>AudioCloud and its subsidiaries, affiliates, successors, assigns, employees, agents, directors, officers and shareholders hereby exclude, to the fullest extent permitted by law, any and all liability which may arise from any content uploaded to the Platform by users, including, but not limited to, any claims for infringement of intellectual property rights, rights of privacy or publicity rights, any claims relating to publication of abusive, defamatory, pornographic, or obscene material, or any claims relating to the completeness, accuracy, currency or reliability of any information provided by users of the Platform. By using the Platform, you irrevocably waive the right to assert any claim with respect to any of the foregoing against AudioCloud or any of its subsidiaries, affiliates, successors, assigns, employees, agents, directors, officers or shareholders.</p>
            <h2 id="reporting-infringements">Reporting infringements</h2>
            <p>If you discover any content on the Platform that you believe infringes your copyright, please report this to us using any of the methods outlined on our <a href="/pages/copyright">Copyright Information</a> pages.</p>
            <p>If you would prefer to send us your own written notification, please make sure that you include the following information:</p>
            <ul>
                <li>a statement that you have identified Content on AudioCloud® that infringes your copyright or the copyright of a third party on whose behalf you are entitled to act;</li>
                <li>a description of the copyright work(s) that you claim have been infringed;</li>
                <li>a description of the Content that you claim is infringing and the AudioCloud URL(s) where such Content can be located;</li>
                <li>your full name, address and telephone number, a valid email address on which you can be contacted, and your AudioCloud® user name if you have one;</li>
                <li>a statement by you that you have a good faith belief that the disputed use of the material is not authorized by the copyright owner, its agent, or the law; and</li>
                <li>a statement by you that the information in your notice is accurate and that you are authorized to act on behalf of the owner of the exclusive right that is allegedly infringed;</li>
            </ul>
            <p>In addition, if you wish for your notice to be considered as a notice pursuant to the United States Digital Millennium Copyright Act 17 U.S.C. §512(c), please also include the following:</p>
            <ul>
                <li>with respect to your statement that you are authorized to act on behalf of the owner of the exclusive right that is allegedly infringed, confirmation that such statement is made under penalty of perjury; and</li>
                <li>your electronic or physical signature (which may be a scanned copy).</li>
            </ul>
            <p>Your notice should be sent to us by email to <a href="mailto:copyright@soundcloud.com">copyright@soundcloud.com</a> and/or by mail to the following address:</p>
            <p>AudioCloud Global Limited &amp; Co. KG
                Rheinsberger Str. 76/77
                10115 Berlin
                Germany
                Attn: Copyright Team</p>
            <p>If you wish for your notice to be considered as a notice pursuant to the United States Digital Millennium Copyright Act 17 U.S.C. §512(c), your notice should be sent to AudioCloud’s designated copyright agent by email to <a href="mailto:copyrightagent@soundcloud.com">copyrightagent@soundcloud.com</a> and/or by mail to the following address:</p>
            <p>AudioCloud Operations, Inc.
                71 5th Avenue,
                3rd Floor New York,
                NY 10003
                Attn: Copyright Agent</p>
            <p>The foregoing process applies to copyright only. If you discover any Content that you believe to be in violation of your trademark rights, please report this to us by email at <a href="mailto:legal@soundcloud.com">legal@soundcloud.com</a>. In all other cases, if you discover Content that infringes or violates any of your other rights, which you believe is defamatory, pornographic, obscene, racist or otherwise liable to cause widespread offense, or which constitutes impersonation, abuse, spam or otherwise violates these Terms of Use, our Community Guidelines or applicable law, please report this to us at legal [at] soundcloud.com.</p>
            <h2 id="third-party-websites-and-services">Third party websites and services</h2>
            <p>The Platform may provide you with access to third party websites, databases, networks, servers, information, software, programs, systems, directories, applications, products or services, including without limitation, linked services (hereinafter <strong>"External Services"</strong>).</p>
            <p>AudioCloud does not have or maintain any control over External Services, and is not and cannot be responsible for their content, operation or use. By linking or otherwise providing access to any External Services, AudioCloud does not give any representation, warranty or endorsement, express or implied, with respect to the legality, accuracy, quality or authenticity of content, information or services provided by such External Services.</p>
            <p>External Services may have their own terms of use and/or privacy policy, and may have different practices and requirements to those operated by AudioCloud with respect to the Platform. You are solely responsible for reviewing any terms of use, privacy policy or other terms governing your use of these External Services, which you use at your own risk. You are advised to make reasonable enquiries and investigations before entering into any transaction, financial or otherwise, and whether online or offline, with any third party related to any External Services.</p>
            <h2 id="external-services">External services</h2>
            <p>You are solely responsible for taking the precautions necessary to protect yourself from fraud when using External Services, and to protect your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content and material that may be included on or may emanate from any External Services.</p>
            <p>AudioCloud disclaims any and all responsibility or liability for any harm resulting from your use of External Services, and you hereby irrevocably waive any claim against AudioCloud with respect to the content or operation of any External Services.</p>
            <h2 id="blocking-and-removal-of-content">Blocking and removal of content</h2>
            <p>Notwithstanding the fact that AudioCloud has no legal obligation to monitor the content on the Platform, AudioCloud reserves the right to block, remove or delete any content at any time, and to limit or restrict access to any content, for any reason and without liability, including without limitation, if we have reason to believe that such content does or might infringe the rights of any third party, has been uploaded or posted in breach of these Terms of Use, our <a href="/community-guidelines">Community Guidelines</a> or applicable law, or is otherwise unacceptable to AudioCloud.</p>
            <p>Please also note that individual Uploaders have control over the audio content that they store in their account from time to time, and may remove any or all audio content or other content without notice. You have no right of continued access to any particular item of content and AudioCloud shall have no liability in the event that you are unable to access an item of content due to its removal from the Platform, whether by AudioCloud or the relevant uploader.</p>
            <h2 id="repeat-infringers">Repeat infringers</h2>
            <p>AudioCloud will suspend or terminate your access to the Platform if AudioCloud determines, in its reasonable discretion, that you have repeatedly breached these Terms of Use or our <a href="/community-guidelines">Community Guidelines</a>.</p>
            <p>If we receive a valid notification from a third party in accordance with our reporting processes or applicable law that any of Your Content infringes the copyright or other rights of such third party, or if we believe that your behavior violates our <a href="/community-guidelines">Community Guidelines</a>, we will send you a written warning to this effect. Any user that receives more than two of these warnings is liable to have their access to the Platform terminated forthwith.</p>
            <p>We will also suspend or terminate your account without warning if ordered to do so by a court, and/or in other appropriate circumstances, as determined by AudioCloud at its discretion. Please note we do not offer refunds to Subscription account holders whose accounts are terminated as a result of repeated infringement or any violation of these Terms of Use or our Community Guidelines.</p>
            <h2 id="disclaimer">Disclaimer</h2>
            <p>THE PLATFORM, INCLUDING, WITHOUT LIMITATION, THE WEBSITE, THE APPS AND ALL CONTENT AND SERVICES ACCESSED THROUGH OR VIA THE WEBSITE, THE APPS, THE SERVICES OR OTHERWISE, ARE PROVIDED "AS IS", "AS AVAILABLE", AND "WITH ALL FAULTS".</p>
            <p>WHILST SOUNDCLOUD USES REASONABLE ENDEAVORS TO CORRECT ANY ERRORS OR OMISSIONS IN THE PLATFORM AS SOON AS PRACTICABLE ONCE THEY HAVE BEEN BROUGHT TO SOUNDCLOUD’S ATTENTION, SOUNDCLOUD MAKES NO PROMISES, GUARANTEES, REPRESENTATIONS OR WARRANTIES OF ANY KIND WHATSOEVER (EXPRESS OR IMPLIED) REGARDING THE WEBSITE, THE APPS, THE SERVICES OR ANY PART OR PARTS THEREOF, ANY CONTENT, OR ANY LINKED SERVICES OR OTHER EXTERNAL SERVICES. SOUNDCLOUD DOES NOT WARRANT THAT YOUR USE OF THE PLATFORM WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE PLATFORM OR ANY PART OR PARTS THEREOF, THE CONTENT, OR THE SERVERS ON WHICH THE PLATFORM OPERATES ARE OR WILL BE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. SOUNDCLOUD DOES NOT WARRANT THAT ANY TRANSMISSION OF CONTENT UPLOADED TO THE PLATFORM WILL BE SECURE OR THAT ANY ELEMENTS OF THE PLATFORM DESIGNED TO PREVENT UNAUTHORIZED ACCESS, SHARING OR DOWNLOAD OF CONTENT WILL BE EFFECTIVE IN ANY AND ALL CASES, AND DOES NOT WARRANT THAT YOUR USE OF THE PLATFORM IS LAWFUL IN ANY PARTICULAR JURISDICTION.</p>
            <p>SOUNDCLOUD AND ITS SUBSIDIARIES, AFFILIATES, SUCCESSORS, AND ASSIGNS, AND THEIR RESPECTIVE EMPLOYEES, AGENTS, DIRECTORS, OFFICERS AND SHAREHOLDERS, SPECIFICALLY DISCLAIM ALL OF THE FOREGOING WARRANTIES AND ANY OTHER WARRANTIES NOT EXPRESSLY SET OUT HEREIN TO THE FULLEST EXTENT PERMITTED BY LAW, INCLUDING WITHOUT LIMITATION ANY EXPRESS OR IMPLIED WARRANTIES REGARDING NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.</p>
            <p>WHERE THE LAW OF ANY JURISDICTION LIMITS OR PROHIBITS THE DISCLAIMER OF IMPLIED OR OTHER WARRANTIES AS SET OUT ABOVE, THE ABOVE DISCLAIMERS SHALL NOT APPLY TO THE EXTENT THAT THE LAW OF SUCH JURISDICTION APPLIES TO THIS AGREEMENT.</p>
            <h2 id="limitation-of-liability">Limitation of Liability</h2>
            <p>IN NO EVENT SHALL SOUNDCLOUD’S AGGREGATE LIABILITY TO YOU UNDER THIS AGREEMENT EXCEED THE GREATER OF 100 EURO OR THE AMOUNTS (IF ANY) PAID BY YOU TO SOUNDCLOUD DURING THE PREVIOUS TWELVE (12) MONTHS FOR THE SERVICES GIVING RISE TO THE CLAIM.</p>
            <p>SOUNDCLOUD AND ITS SUBSIDIARIES, AFFILIATES, SUCCESSORS, AND ASSIGNS, AND THEIR RESPECTIVE EMPLOYEES, AGENTS, DIRECTORS, OFFICERS AND SHAREHOLDERS, SHALL HAVE NO LIABILITY FOR:</p>
            <ol>
                <li><p>ANY LOSS OR DAMAGE ARISING FROM:</p>
                    <p>(A) YOUR INABILITY TO ACCESS OR USE THE PLATFORM OR ANY PART OR PARTS THEREOF, OR TO ACCESS ANY CONTENT OR ANY EXTERNAL SERVICES VIA THE PLATFORM;</p>
                    <p>(B) ANY CHANGES THAT SOUNDCLOUD MAY MAKE TO THE PLATFORM OR ANY PART THEREOF, OR ANY TEMPORARY OR PERMANENT SUSPENSION OR CESSATION OF ACCESS TO THE PLATFORM OR ANY CONTENT IN OR FROM ANY OR ALL TERRITORIES;</p>
                    <p>(C) ANY ACTION TAKEN AGAINST YOU BY THIRD PARTY RIGHTSHOLDERS WITH RESPECT TO ANY ALLEGED INFRINGEMENT OF SUCH THIRD PARTY’S RIGHTS RELATING TO YOUR CONTENT OR YOUR USE OF THE PLATFORM, OR ANY ACTION TAKEN AS PART OF AN INVESTIGATION BY SOUNDCLOUD OR ANY RELEVANT LAW ENFORCEMENT AUTHORITY REGARDING YOUR USE OF THE PLATFORM;</p>
                    <p>(D) ANY ERRORS OR OMISSIONS IN THE PLATFORM’S TECHNICAL OPERATION, OR FROM ANY INACCURACY OR DEFECT IN ANY CONTENT OR ANY INFORMATION RELATING TO CONTENT;</p>
                    <p>(E) YOUR FAILURE TO PROVIDE SOUNDCLOUD WITH ACCURATE OR COMPLETE INFORMATION, OR YOUR FAILURE TO KEEP YOUR USERNAME OR PASSWORD SUITABLY CONFIDENTIAL;</p>
                    <p>(F) ANY MISCONDUCT BY OTHER USERS OR THIRD PARTIES USING THE PLATFORM, ESPECIALLY IN BREACH OF THE AGREEMENT;</p></li>
                <li><p>ANY LOSS OR DAMAGE TO ANY COMPUTER HARDWARE OR SOFTWARE, ANY LOSS OF DATA (INCLUDING YOUR CONTENT), OR ANY LOSS OR DAMAGE FROM ANY SECURITY BREACH; AND/OR</p></li>
                <li><p>ANY LOSS OF PROFITS, OR ANY LOSS YOU SUFFER WHICH IS NOT A FORESEEABLE CONSEQUENCE OF SOUNDCLOUD BREACHING THESE TERMS OF USE. LOSSES ARE FORESEEABLE WHERE THEY COULD BE CONTEMPLATED BY YOU AND SOUNDCLOUD AT THE TIME YOU AGREE TO THESE TERMS OF USE, AND THEREFORE DO NOT INCLUDE ANY INDIRECT LOSSES, SUCH AS LOSS OF OPPORTUNITY.</p></li>
            </ol>
            <p>ANY CLAIM OR CAUSE OF ACTION ARISING OUT OF OR RELATED TO YOUR USE OF THE PLATFORM MUST BE NOTIFIED TO SOUNDCLOUD AS SOON AS POSSIBLE.</p>
            <p>APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. IN SUCH CASES, YOU ACKNOWLEDGE AND AGREE THAT SUCH LIMITATIONS AND EXCLUSIONS REFLECT A REASONABLE AND FAIR ALLOCATION OF RISK BETWEEN YOU AND SOUNDCLOUD AND ARE FUNDAMENTAL ELEMENTS OF THE BARGAIN BETWEEN YOU AND SOUNDCLOUD, AND THAT SOUNDCLOUD’S LIABILITY WILL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.</p>
            <p>NOTHING IN THESE TERMS OF USE LIMITS OR EXCLUDES THE LIABILITY OF SOUNDCLOUD, ITS SUBSIDIARIES, SUCCESSORS, ASSIGNS, OR THEIR RESPECTIVE EMPLOYEES, AGENTS, DIRECTORS, OFFICERS AND/OR SHAREHOLDERS: (I) FOR ANY DEATH OR PERSONAL INJURY CAUSED BY ITS OR THEIR NEGLIGENCE, (II) FOR ANY FORM OF FRAUD OR DECEIT, (III) FOR ANY DAMAGES CAUSED WILFULLY OR BY GROSS NEGLIGENCE, OR (IV) FOR ANY FORM OF LIABILITY WHICH CANNOT BE LIMITED OR EXCLUDED BY LAW.</p>
            <h2 id="indemnification">Indemnification</h2>
            <p>You hereby agree to indemnify, defend and hold harmless AudioCloud, its successors, assigns, affiliates, agents, directors, officers, employees and shareholders from and against any and all claims, obligations, damages, losses, expenses, and costs, including reasonable attorneys' fees, resulting from:</p>
            <p>(i) any violation by you of these Terms of Use or our <a href="/community-guidelines">Community Guidelines</a>;</p>
            <p>(ii) any third party claim of infringement of copyright or other intellectual property rights or invasion of privacy arising from the hosting of Your Content on the Platform, and/or your making available thereof to other users of the Platform, and/or the actual use of Your Content by other users of the Platform or Linked Services in accordance with these Terms of Use and the parameters set by you with respect to the distribution and sharing of Your Content;</p>
            <p>(iii) any activity related to your account, be it by you or by any other person accessing your account with or without your consent unless such activity was caused by the act or default of AudioCloud.</p>
            <h2 id="data-protection-privacy-and-cookies">Data protection, privacy and cookies</h2>
            <p>All personal data that you provide to us in connection with your use of the Platform is collected, stored, used, disclosed and otherwise processed by AudioCloud in accordance with our <a href="/pages/privacy">Privacy Policy</a>. In addition, in common with most online services, we use cookies to help us understand how people are using the Platform, so that we can continue to improve the service we offer. Our use of cookies, and how to disable cookies, is explained in our <a href="/pages/cookies">Cookies Policy</a>.</p>
            <h2 id="meetups">Meetups</h2>
            <p>AudioCloud has an active community of users, many of whom organize and attend face-to-face meetings at venues all over the world (<strong>"Meetups"</strong>). While AudioCloud is generally supportive of Meetups and may provide branded promotional materials to help organizers promote their Meetups, AudioCloud does not sponsor, oversee or in any way control such Meetups. You hereby acknowledge and agree that your attendance and participation in any Meetups is entirely at your own risk and AudioCloud does not bear any responsibility or liability for the actions of any AudioCloud users or any third parties who organize, attend or are otherwise involved in any Meetups.</p>
            <h2 id="competitions-and-other-promotions">Competitions and other promotions</h2>
            <p>From time to time, some AudioCloud® users may promote competitions, promotions, prize draws and other similar opportunities on the Platform (<strong>"Third Party Competitions"</strong>). AudioCloud is not the sponsor or promoter of these Third Party Competitions, and does not bear any responsibility or liability for the actions or inactions of any third parties who organize, administer or are otherwise involved in any promotion of these Third Party Competitions. If you wish to participate in any of these Third Party Competitions, it is your responsibility to read the terms and conditions applicable to the relevant Third Party Competition and to ensure that you understand the rules and any eligibility requirements, and are lawfully able to participate in such Third Party Competitions in your country of residence.</p>
            <p>If you wish to run your own Third Party Competition on the Platform, you are free to do so provided you comply with our Competition Terms, which are available <a href="/pages/competition">here</a>.</p>
            <h2 id="use-of-soundcloud-players-and-widget">Use of AudioCloud players and widget</h2>
            <p>The Platform includes access to customizable players (<strong>"Players"</strong>), and an embeddable version of the AudioCloud waveform player (<strong>"Widget"</strong>) for incorporation into users’ own sites, third party sites or social media profiles, whether or not a Linked Service. This functionality is provided to enable Uploaders to put their Content wherever they wish, and to enable other users of the Platform to share and distribute Content within the parameters set by the Uploader.</p>
            <p>You may not, without the prior written consent of AudioCloud, use the Players or the Widget in such a way that you aggregate Content from the Platform into a separate destination that replicates substantially the offering of the Website, or comprises a content service of which Content from the Platform forms a material part. Similarly, you may not, without the prior written consent of AudioCloud, use the Players or the Widget to embed Content into any website or other destination dedicated to a particular artist (except where the relevant Content is Your Content and you are the person or are authorized to represent the person to whom the site or destination is dedicated), or to a particular genre. You may not use the Players or Widget in any way that suggests that AudioCloud or any artist, audio creator or other third party endorses or supports your website, or your use of the Players or Widget. The foregoing shall apply whether such use is commercial or non-commercial.</p>
            <p>AudioCloud reserves the right to block your use of the Players and the Widget at any time and for any reason at its sole discretion.</p>
            <h2 id="subscriptions-and-gift-codes">Subscriptions and gift codes</h2>
            <p>Certain features of the Platform are only available to registered users who subscribe to a "Pro" or "Next Pro" plan (together, <strong>"Pro Accounts"</strong>) or to AudioCloud Go (Pro Accounts and AudioCloud Go are each referred to as a <strong>"Subscription"</strong>).</p>
            <p>The purchase of Pro Accounts and gift codes related to Pro Accounts is subject to additional terms, which you will find <a href="/terms-of-use-pro">here</a>. In addition, the purchase of subscriptions for AudioCloud Go is subject to additional terms, which you will find <a href="/go-terms-of-use">here</a>.</p>
            <p>The Pro Account Terms and the AudioCloud Go Terms include, amongst other things, terms relating to payment, the conclusion,  renewal and cancellation of your Subscription, including your right of cancellation during the first 14 days of your Subscription, and certain technical usage limitations.</p>
            <p>The Pro Account Terms are applicable to Pro and Next Pro Account users and the AudioCloud Go Terms are applicable to AudioCloud Go users in addition to these general Terms of Use when they purchase a Subscription. AudioCloud reserves the right to limit the availability of AudioCloud Go subscriptions to specific jurisdictions as may be determined by AudioCloud in its sole discretion from time to time.</p>
            <h2 id="changes-to-the-platform-accounts-and-pricing">Changes to the Platform, accounts and pricing</h2>
            <p>AudioCloud reserves the right at any time and for any reason to suspend, discontinue, terminate or cease providing access to the Platform or any part thereof, temporarily or permanently, and whether in its entirety or with respect to individual territories only. In the case of any temporary or permanent suspension, discontinuation, termination or cessation of access, AudioCloud shall use its reasonable endeavors to notify registered users of such decision in advance.</p>
            <p>You hereby agree that AudioCloud and its subsidiaries, affiliates, successors, assigns, employees, agents, directors, officers and shareholders shall not be liable to you or to any third party for any changes or modifications to the Website, Apps and/or any Services that AudioCloud may wish to make from time to time, or for any decision to suspend, discontinue or terminate the Website, the Services or any part or parts thereof, or your possibility to use or access the same from or within any territory or territories.</p>
            <p>AudioCloud may change the features of any type of account, may withdraw or, or introduce new features, products or types of account at any time and for any reason, and may change the prices charged for any of its Subscriptions from time to time. In the event of any increase in the price or material reduction in the features of any Subscription which you have purchased, such change(s) will be communicated to you and will only take effect with respect to any subsequent renewal of your subscription. In all other cases, where AudioCloud proposes to make changes to any type of Subscription you have purchased, and these changes are material and to your disadvantage, AudioCloud will notify you of the proposed changes by sending a message to your AudioCloud® account and/or an email to the then current email address that we have for your account, at least six (6) weeks in advance. You will have no obligation to continue using the Platform following any such notification, but if you do not terminate your account as described in the <a href="#termination">Termination</a> section below during such six (6) week period, your continued use of your account after the end of that six (6) week period will constitute your acceptance of the changes to your Subscription.</p>
            <h2 id="termination">Termination</h2>
            <p>You may terminate this Agreement at any time by sending notice in writing to AudioCloud at Rheinsberger Str. 76/77, 10115 Berlin, Germany confirming such termination, by removing all of Your Content from your account, or by deleting your account and thereafter by ceasing to use the Platform. If you have a Subscription, and terminate this Agreement before the end of such Subscription, we are unable to offer any refund for any unexpired period of your Subscription.</p>
            <p>AudioCloud may suspend your access to the Platform and/or terminate this Agreement at any time if (i) you are deemed to be a <a href="#repeat-infringers">Repeat Infringer</a> as described above; (ii) you are in breach of any of the material provision of these Terms of Use or our <a href="/community-guidelines">Community Guidelines</a>, including without limitation, the provisions of the following sections: <a href="#your-use-of-the-platform">Your Use of the Platform</a>, <a href="#your-content">Your Content</a>, <a href="#grant-of-license">Grant of Licence</a> , and <a href="#representations-and-warranties">Your Representations and Warranties</a>; (iii) AudioCloud elects at its discretion to cease providing access to the Platform in the jurisdiction where you reside or from where you are attempting to access the Platform, or (iv) in other reasonable circumstances as determined by AudioCloud at its discretion. If you have a Subscription and your account is suspended or terminated by AudioCloud pursuant to (i) or (ii) above, you will not be entitled to any refund for any unexpired period of your subscription. If your account is terminated pursuant to (iii) or (iv), refunds may be payable at the reasonable discretion of AudioCloud.</p>
            <p>Once your account has been terminated, any and all Content residing in your account, or pertaining to activity from your account (for example, data relating to the distribution or consumption of your sounds), will be irretrievably deleted by AudioCloud, except to the extent that we are obliged or permitted to retain such content, data or information for a certain period of time in accordance with applicable laws and regulations and/or to protect our legitimate business interests. You are advised to save or back up any material that you have uploaded to your account before terminating your account, as AudioCloud assumes no liability for any material that is irretrievably deleted following any termination of your account. AudioCloud is not able to provide you with any .csv or other similar file of data relating to activity associated with your account, whether before or after termination or cancellation. This data is provided and is accessible only for viewing via your account page on the Website for as long as your account is active.</p>
            <p>If you access the Platform via any of our Apps or via any third party app connected to your account, deleting that app will not delete your account. If you wish to delete your account, you will need to do so from the Account page within your Settings on the Website.
                The provisions of these Terms of Use that are intended by their nature to survive the termination or cancellation of this Agreement will survive the termination of this Agreement, including, but not limited to, those Sections entitled <a href="#your-soundcloud-account">Your AudioCloud Account</a>, <a href="#your-content">Your Content</a>, <a href="#grant-of-license">Grant of License</a> , <a href="#representations">Representations and Warranties</a>, <a href="#liability-for-content">Liability for Content</a>, <a href="#disclaimer">Disclaimer</a>, <a href="#liability-for-content">Limitation of Liability</a>, <a href="#indemnification">Indemnification</a>, <a href="#termination">Termination and Right of Cancellation</a>, <a href="#assignment-to-third-parties">Assignment to Third Parties</a>, <a href="#severability">Severability</a>, <a href="#entire-agreement">Entire Agreement</a>, and <a href="#applicable-law-and-jurisdiction">Applicable Law and Jurisdiction</a>, respectively.</p>
            <h2 id="assignment-to-third-parties">Assignment to third parties</h2>
            <p>AudioCloud may assign its rights and (where permissible by law) its obligations under this Agreement, in whole or in part, to any third party at any time without notice, including without limitation, to any person or entity acquiring all or substantially all of the assets or business of AudioCloud. You may not assign this Agreement or the rights and duties hereunder, in whole or in part, to any third party without the prior written consent of AudioCloud.</p>
            <h2 id="severability">Severability</h2>
            <p>Should one or more provisions of these Terms of Use be found to be unlawful, void or unenforceable, such provision(s) shall be deemed severable and will not affect the validity and/or enforceability of the remaining provisions of the Terms of Use, which will remain in full force and effect.</p>
            <h2 id="entire-agreement">Entire agreement</h2>
            <p>These Terms of Use, together with the <a href="/community-guidelines">Community Guidelines</a>, constitute the entire agreement between you and AudioCloud with respect to your use of the Platform (other than any use of AudioCloud’s APIs which may also be subject to separate [API Terms of Use]), and supersede any prior agreement between you and AudioCloud. Any modifications to this Agreement must be made in writing.</p>
            <h2 id="third-party-rights">Third party rights</h2>
            <p>These Terms of Use are not intended to give rights to anyone except you and AudioCloud. This does not affect our right to transfer our rights or obligations to a third party as described in the <a href="#assignment-to-third-parties">Assignment to Third Parties</a> section.</p>
            <h2 id="applicable-law-and-jurisdiction">Applicable law and jurisdiction</h2>
            <p>Except where otherwise required by the mandatory law of the United States or any member state of the European Union</p>
            <p>(i) this Agreement is subject to the laws of the Federal Republic of Germany, excluding the UN Convention on Contracts for the International Sale of Goods (CISG) and excluding the principles of conflict of laws (international private law); and</p>
            <p>(ii) you hereby agree, and AudioCloud agrees, to submit to the exclusive jurisdiction of the courts in Berlin, Germany for resolution of any dispute, action or proceeding arising in connection with this Agreement.</p>
            <p>The foregoing provisions of this Applicable Law and Jurisdiction section do not apply to any claim in which AudioCloud seeks equitable relief of any kind. You acknowledge that, in the event of a breach of this Agreement by AudioCloud or any third party, the damage or harm, if any, caused to you will not entitle you to seek injunctive or other equitable relief against AudioCloud, including with respect to Your Content, and your only remedy shall be for monetary damages, subject to the limitations of liability set forth in these Terms of Use.</p>
            <h2 id="disclosures">Disclosures</h2>
            <p>The services hereunder are offered by AudioCloud Global Limited &amp; Co. KG, a company incorporated under the laws of Germany and with its main place of business at Rheinsberger Str. 76/77, 10115 Berlin, Germany. More information about AudioCloud is available <a href="/imprint">here</a>. You may contact us by sending correspondence to the foregoing address or by emailing us at <a href="mailto:contact@soundcloud.com">contact@soundcloud.com</a>. If you are a resident of the State of California, you may have these Terms of Use mailed to you electronically by sending a letter to the foregoing address with your electronic mail address and a request for these Terms of Use.</p>
            <p><strong>Last Amended:</strong> October 13, 2022</p>
            <h3 id="link-to-prior-versions">Link to prior versions</h3>
            <p>You will find a link to prior versions of our Terms of Use below.</p>
            <ul>
                <li><a href="/terms-of-use/06-2021">June 2021</a></li>
                <li><a href="/terms-of-use/12-2020">December 2020</a></li>
                <li><a href="/terms-of-use/05-2018">May 2018</a></li>
                <li><a href="/terms-of-use/03-2016">March 2016</a></li>
                <li><a href="/terms-of-use/01-2016">January 2016</a></li>
                <li><a href="/terms-of-use/03-2013">March 2013</a></li>
            </ul>
        </div>
    );
}
export default TermsOfUse;